### ISSUE TITLE
Don't auto focus the input field when page loads

### ISSUE THREAD

**Issue by tony-mak** [scrollback/scrollback#146]
The current behaviour is that when page loads, the input field would being focused.

The relevant line is in:
https://github.com/scrollback/scrollback/blob/master/ui/compose.js#L38

I think this behaviour is quite annoying, especially if the chatroom is embedded in a page with scrollbar. It would make the page scroll to the bottom.

I suggest turning if off by default and of coz it is better if we can configure this.

Thank you.

**Comment by ming030890** [comment]
Somehow it is broken in the recent release.

I have create a simple demo for the bug:
http://jsbin.com/wukuvivoro/1/edit?html,output
You can see that the chatroom is get focused even it is minimized.
