### ISSUE TITLE
Error embedding Scrollback.io in the canvas form

### ISSUE THREAD

**Issue by spencerthayer** [scrollback/scrollback#266]
container:"scrollback-container",position:"custom"
container:"canvas=form",position:"custom"

Essentially there is no documentation in the repository on how to properly embed Scrollback.io much less how to use the script as canvas=form.

Thanks

**Comment by timeseer** [comment]
This bug occured again. Even [upper example](http://codepen.io/satya164/pen/zsCec) is broken too.
The iframe is putted under `body` tag not `#scrollback-container`.
I tested that in Chrome 50.
