### ISSUE TITLE
Installation issues - missing dependancies, gruntfile missing

### ISSUE THREAD

**Issue by JourneymanGeek** [scrollback/scrollback#412]
I'm running ubuntu 14.04 on a VM to try to get a test install of scrollback running. I used the install script on github ( wget https://raw.githubusercontent.com/scrollback/scrollback/master/tools/install.sh -O install.sh && chmod +x install.sh && ./install.sh) and *should* be using the latest version available there as of 27th november 

I've needed to install the following npm packages manually
gulp 
del
bower
browserify
vinyl-source-stream
vinyl-buffer
event-stream
lazypipe
gulp-plumber
gulp-util
gulp-jshint
gulp-gitmodified

And sass using the command sudo gem install sass

Isn't the installer supposed to handle these?

I've also faced the second issue that the user here has had https://github.com/scrollback/scrollback/issues/66. I tried running grunt to get the stylesheets and such running, but apparently I lack a gruntfile or grunt hasn't been installed locally to the project - can I get around this somehow?

**Comment by sindhus** [comment]
@JourneymanGeek hi! this issue was opened awhile back, were you since then able to get Scrollback running locally? We also updated our package.json recently thus fixing #516. Perhaps you shoud try installing again if you haven't? :)
