### ISSUE TITLE
Particular profile for Scrollback buddies and Scrollback campus ambassador 

### ISSUE THREAD

**Issue by dbbhattacharya** [scrollback/scrollback#450]
Is it possible to create separate profiles for each scrollback buddies and srollback campus ambassadors? It will encourage them to contribute more to scrollback.

**Comment by aravindet** [comment]
This is possible, but I suggest that it be done outside of Scrollback. In fact I believe an entire campus program portal with profiles, leaderboards etc. may be on the way, created by campus ambassadors themselves. Please contact @priyankanag for more details.

Closing this as it is not a Scrollback open source project issue.
