### ISSUE TITLE
Multiple messages.

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#458]
![bug-scrollback](https://cloud.githubusercontent.com/assets/6933389/5648921/3197e5ee-96b8-11e4-8397-c39f21682fb3.png)

During conversation I was able to receive the messages properly. But after sometime I just scrolled back to read the messages again. I was surprised to see multiple appearance of the same messages. 
Actually, those messages were sent only once.

**Comment by aravindet** [comment]
@amalantony, this is most likely due to incorrect merging of getTexts
results into localStorage. If this is a quick fix, please do now.

aravind.
