### ISSUE TITLE
esper.net irc invite ignored?

### ISSUE THREAD

**Issue by CyanPrime** [scrollback/scrollback#459]
So when I type
/invite scrollback #strangecoast
on
esper.net's irc server as OP in #strangecoast
nothing happens.

I've tried it a bunch, but nothing ever happens.

Enable IRC is clicked, the irc server is set to irc.esper.net
the room is set to #strangecoast

So what gives?

**Comment by aravindet** [comment]
Esper.net seems to have K-lined our server, we’ll need to talk to them and figure out why. Do you know any of the ircops?

**Comment by aravindet** [comment]
I’ve reached the esper.net operators, and I’m hopeful that it will be resolved soon.

**Comment by CyanPrime** [comment]
So did this ever get fixed?

**Comment by execclouds** [comment]
I get "scrollback: No such nick/channel" on irc.rizon.net
Is this the same issue?
