### ISSUE TITLE
Hyperlink support in "i" information(description) section on chat rooms.

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#460]
![hyperlink - scrollback](https://cloud.githubusercontent.com/assets/6933389/5666783/3667dbbc-9788-11e4-9881-824480614424.png)

It would helpful if "i" information section on the chat room supports hyperlink. It would be easy by just clicking on that url(hyperlink) rather than copying and pasting the url in new tab.

**Comment by satya164** [comment]
It is in production now.

**Comment by sagarhani** [comment]
![hover](https://cloud.githubusercontent.com/assets/6933389/7102370/1fe42cc6-e09c-11e4-96ca-278ead88c860.png)
Again hyperlinks are not supported in description section.
