### ISSUE TITLE
[CSS] Message input box placeholder shouldn't be selectable

### ISSUE THREAD

**Issue by nighto** [scrollback/scrollback#480]
Hello,

the message input box placeholder shouldn't be selectable. I just found out by trying to paste some text on the box.

![image](https://cloud.githubusercontent.com/assets/397851/6012264/39fbf55c-ab2d-11e4-87bf-15446a884298.png)

I think it could be solved by adding ```user-select: none; -webkit-user-select: none;``` on CSS.

**Comment by aravindet** [comment]
@satya164 Seems reasonable.

**Comment by aravindet** [comment]
Merged; will be released later today.

**Comment by nighto** [comment]
Thanks for such a quick fix! =)
