### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by skynet** [scrollback/scrollback#481]
Would be helpful to have some better README.md and/or another documentation (at github pages or so). And how about instruction to INSTALL.

**Comment by aravindet** [comment]
I agree that there should be better documentation, especially around setting up a developer environment and server configs.

Documentation on using the hosted Scrollback service (including the APIs for integrating it with your site) and design docs are in the [wiki](/scrollback/scrollback/wiki).

**Comment by sindhus** [comment]
@skynet hi! I have just proposed PR #527. It includes instructions on how to install Scrollback locally and has link to our wiki that explains Scrollback architecture. Is there anything else we missed? Let us know :)

**Comment by sindhus** [comment]
We have a new README.md and a better tools/install.sh. Try it out and let us know if you have more issues.

**Comment by skynet** [comment]
:+1:
