### ISSUE TITLE
Emojis are not supporting in the "All discussions" section.

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#492]
![scrollback_bug](https://cloud.githubusercontent.com/assets/6933389/6085605/50413552-ae61-11e4-9ac3-f8bee2078f08.png)

In your recent update, it is really good to see those colorful emojis in the chat section. :+1: 
But those emojis are not supporting in the "All discussions" section. We can just see unicode of those emojis.
Sorry to say, Not looking nice. :-1:

**Comment by satya164** [comment]
The issue is no longer relevant.
