### ISSUE TITLE
Device specific configs.

### ISSUE THREAD

**Issue by karthikb351** [scrollback/scrollback#496]
Is there a way to set the widget to be minimized on a phone/tablet but expanded on larger devices?

**Comment by satya164** [comment]
You could dynamically set the "minimize" option to "true" using Javascript.

But yes, I think we could minimize by default on mobile devices. @aravindet ?

**Comment by karthikb351** [comment]
It's a recurring feedback I've got from friends when I told them about scrollback(who are both using it as well as embedding it themselves).

**Comment by aravindet** [comment]
This is sensible. It should be minimized by default on all platforms.

aravind.
