### ISSUE TITLE
widget minimization

### ISSUE THREAD

**Issue by DreadKnight** [scrollback/scrollback#507]
There seems to be a regression in the latest version(s) and now the embedded widget can no longer be minimized by clicking its header.

**Comment by seiyria** [comment]
I'm also having this issue, among others.

**Comment by aravindet** [comment]
We aren’t able to reproduce this, could you link to your page please?

**Comment by seiyria** [comment]
@aravindet Mine is http://webfe.idle.land (also linked in #425)

**Comment by DreadKnight** [comment]
Mine is https://AncientBeast.com - minimization seems to work fine now, well done!
