### ISSUE TITLE
no log from IRC

### ISSUE THREAD

**Issue by DreadKnight** [scrollback/scrollback#508]
I recall the embedded widget used to show the messages written in the IRC room. When you write in the widget the text shows up on IRC, but not the other way around as well. This is broken for quite a while now. At least for #AncientBeast on Freenode. You can try it out, here's the website as well https://AncientBeast.com

**Comment by seiyria** [comment]
This happens intermittently with my project as well. As for when it starts working again, it's totally random.

**Comment by aravindet** [comment]
We’re trying to figure this one out. This is related to IRC netsplits. For some reason the bot does not seem to rejoin some channels after the netsplit is resolved.

As a workaraound, please toggle the "enable" switch for under IRC in your room configurations.

**Comment by DreadKnight** [comment]
Which doesn't really work for me, as the spinner near the "Done" button is forever there.
