### ISSUE TITLE
User profile picture and search icon will disappear.

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#515]
If we click on the Chat room name, the user profile picture and the seach icon will be hidden. We need to click again on the chat room name to make it visible. 
![chat-room-bug](https://cloud.githubusercontent.com/assets/6933389/6419325/201df338-bee2-11e4-8191-74dbdd0d6d69.png)

**Comment by aravindet** [comment]
This happens because the toast-minimize class gets applied when that is clicked.

**Comment by aravindet** [comment]
Fixed in new version
