### ISSUE TITLE
Same icons

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#524]
![icons](https://cloud.githubusercontent.com/assets/6933389/6652529/c3893738-ca97-11e4-8464-1808eaf5e1d5.png)

Both the icons looks exactly same.
Shall I use any suitable Glyphicons ( :warning: , :grey_exclamation: , :exclamation: ) and change the icon for Report issue ?

**Comment by sindhus** [comment]
@sagarhani We have a new UI coming soon and this should not be an issue in it.

**Comment by aravindet** [comment]
Fixed in new UI
