### ISSUE TITLE
Issue while scrolling down.

### ISSUE THREAD

**Issue by SamJon** [scrollback/scrollback#528]
I'm facing this problem with the new UI. 
When we scroll down, it goes to the bottom and comes back to initial position..!

**Comment by sagarhani** [comment]
Yes, even I'm facing the similar problem in the new UI.
"Scroll to bottom" button doesn't work. We need to scroll down using the scrollbar.

**Comment by abhijainn27** [comment]
Scroll to bottom works !! But it only works for the current messages that you are viewing instead it should take you to the last message in the discussion.

**Comment by aravindet** [comment]
Fixed.
