### ISSUE TITLE
Same title for all chat rooms

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#529]
![scrollback-title](https://cloud.githubusercontent.com/assets/6933389/6689041/c752fc9e-ccdd-11e4-9e56-998d6bdf8e13.png)

The title of the webpage(Chat room) remains same no matter which ever chat room you visit.
It always shows "scrollback on Scrollback" as highlighted in the above image. :arrow_up: 
In the previous UI, the title used to change. If we are on "campus-ambassador" chat room the title would be "campus-ambassador on scrollback".

**Comment by aravindet** [comment]
Good catch. Fixing soon.

**Comment by aravindet** [comment]
Fixed
