### ISSUE TITLE
Overwriting of text

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#532]
![overwrite](https://cloud.githubusercontent.com/assets/6933389/6710793/10b99192-cda9-11e4-8b48-0d2f5d960d2a.png)

Just type few characters in the text box (do not press enter). Click anywhere on the screen or just select new tab and come back to previous tab(chat room tab). The text which you had typed will be overwritten by the word "QUCIK REPLY".

**Comment by satya164** [comment]
Noted

**Comment by sagarhani** [comment]
This problem occurs even if we are pasting anything on the text box using shortcut keys.
1. Click on the text box.
2. Ctrl + V to paste.
3. It gets overwritten.

**Comment by satya164** [comment]
Fixed.
