### ISSUE TITLE
No back button! 

### ISSUE THREAD

**Issue by AkshayTiwari** [scrollback/scrollback#544]
If you can see the images. Once you click the profile button it takes you to your profile but you can't go back to the home page. 

Images: 

![capture](https://cloud.githubusercontent.com/assets/8322582/6754811/e5bbbc8e-cf44-11e4-8360-584e6fa7ca72.PNG)
![1](https://cloud.githubusercontent.com/assets/8322582/6754828/06ae3cfa-cf45-11e4-937f-fe2cf4bebc54.PNG)

**Comment by satya164** [comment]
What do you mean by the home page? The profile page is the homepage.

**Comment by AkshayTiwari** [comment]
i meant, once i to second image. i dont find any button which can get the room names to my left and not my image.

**Comment by satya164** [comment]
The rooms are listed as big cards.

**Comment by aravindet** [comment]
This should be treated as ui feedback, not a bug report.

**Comment by asdofindia** [comment]
If this is a ui feedback, where should it be sent? I was going to file this UI "bug" but just went through the closed issues to see exactly this.

**Comment by aravindet** [comment]
We have it already, its on our whiteboard :-)
