### ISSUE TITLE
Not able to visit/create a chat room from the home page

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#550]
![visit-rooom](https://cloud.githubusercontent.com/assets/6933389/6811501/6a3a549c-d28e-11e4-88a1-864effa98761.png)

It asks us to type the name of the chat room. If we give the room name as ```2-2``` it shows an error - Room name must start with a lower case letter or digit instead of taking us to room : https://scrollback.io/2-2
Also, it is not asking us to create a new room if it doesn't exist!

**Comment by sagarhani** [comment]
I just found this!
We are not able to create/visit any room starting with a digit (even lower case letters along with digit at the beginning) from the home page.

**Comment by aravindet** [comment]
Yup, that's the intended behavior.
