### ISSUE TITLE
Title of the chat room changes

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#556]
This is the correct one.

![title-1](https://cloud.githubusercontent.com/assets/6933389/6848645/72f04684-d3f4-11e4-96f6-07ea449771f5.png)

In any chat rooms, if we open "All messages".

![title-2](https://cloud.githubusercontent.com/assets/6933389/6848651/7fbfac7e-d3f4-11e4-8cc5-edc9f79b292c.png)

If we scrollback and click on any message.

![title-3](https://cloud.githubusercontent.com/assets/6933389/6848655/8bfaa246-d3f4-11e4-8c0a-dda3d37abfde.png)

**Comment by aravindet** [comment]
Fixed
