### ISSUE TITLE
broken embed

### ISSUE THREAD

**Issue by DreadKnight** [scrollback/scrollback#573]
Not sure what happened recently, but the embed of scrollback on my website no longer works. I can't manage to edit my room from the official scrollback.io website, not to mention finding some new embed come. I guess the new version has a ton of regressions or something. Check out https://AncientBeast.com

**Comment by satya164** [comment]
Hey, embed seems to be working fine here. Can you try clearing your cache and see if the issues persist?

Also, what exactly is not working?

**Comment by DreadKnight** [comment]
Cleared cache, everything works fine it seems, my bad :D
