### ISSUE TITLE
Remove logs from Google searches

### ISSUE THREAD

**Issue by ljharb** [scrollback/scrollback#628]
Please remove all channel logs from Google searches. You're not authorized to record them, but especially not to make them searchable.

**Comment by aravindet** [comment]
Which channel is this?

A chanop must invite the bot before it joins. Chanops can also kick the bot
and it won't rejoin. We can bulk delete logs on request, but you have to
tell us the name of the channel.

**Comment by ljharb** [comment]
Thanks for the clarification and response. If an op had to invite the bot, then I'll discuss it with them before continuing here.
