### ISSUE TITLE
Recommend/Require users to set a nick before beginning to speak on channel

### ISSUE THREAD

**Issue by hyperair** [scrollback/scrollback#65]
It can be pretty confusing when a legion of sb-blah users appear on the channel and start talking at the same time. Please recommend users to set a nickname before posting, and store it persistently, as a cookie or something, even if they haven't registered for a scrollback.io account.

**Comment by aravindet** [comment]
The current behavior is a good compromise; your community can choose between (1) frictionless auto-join with anonymous users or (2) require registrations and ensure people have nicknames.
