### ISSUE TITLE
The "thread" embed option seems to be broken

### ISSUE THREAD

**Issue by vrinek** [scrollback/scrollback#664]
Reading https://github.com/scrollback/scrollback/wiki/Embed-Options#thread, I understand that I can create arbitrary threads in my room. This is how I tried to do it:

```javascript
window.scrollback = {
    "room": "my-room-128",
    "form": "toast",
    "minimize": true,
    "thread": "a-new-discussion",
};
```

When I visit my webpage, I see the widget and in the top bar instead of the thread name, it is blank.

If I type something and press enter, I don't see the message on that same widget but it appears on the scrollback page of my room's "all messages". Then, if I reload I see my previous message in the widget. If I type something and press enter, I see it fine. Then, if I change the thread in my embed options and try again, type something, reload, I see the message I typed as the thread's name and a new thread has been created in my room's page.

Browser: Firefox 37 on OSX 10.10

**Comment by aravindet** [comment]
Creating new threads using the embed API is unsupported; it can be used to embed existing threads using their ID (it appears in the URL when you navigate to a page).

Automatically creating new threads may be supported at a later date.
