### ISSUE TITLE
signed up with email, now cannot log-out of a irc channel with that nick

### ISSUE THREAD

**Issue by philipp-sumo** [scrollback/scrollback#710]
hello, i've signed in with a mail address in order to set a custom nickname in an irc channel. now i see no way of leaving that channel again (/quit doesn't work).

**Comment by aravindet** [comment]
Close all Scrollback tabs and it will leave the channel in about a minute.

The delay is so that it will not part and rejoin if you refresh the page.

Aravind

**Comment by philipp-sumo** [comment]
in my case the nick stays present in the channel even days after i've logged out of scrollback/closed all tabs...
