### ISSUE TITLE
Not able to integrate with Twitter hashtag

### ISSUE THREAD

**Issue by sagarhani** [scrollback/scrollback#770]
By clicking on ``` SIGN IN TO TWITTER ``` button will open a new window with this [URL](https://scrollback.io/r/twitter/r). 

![twitter-integration](https://cloud.githubusercontent.com/assets/6933389/8499958/787f0392-21b5-11e5-85f4-0ddf4cae3f49.png)

**Comment by aravindet** [comment]
Fixed
