### ISSUE TITLE
Login to Google doesn't work

### ISSUE THREAD

**Issue by metao1** [scrollback/scrollback#924]
Hi all,
I just wonder of how Google sign-in works. It always redirects from <code> https://example.com/r/google/login </code> to 
<code>https://example.com/r/google</code>
Any suggestion or configuration before deployment?
Thanks in advance
Metao

**Comment by aravindet** [comment]
You should create a project in the [Google developer console](https://console.developers.google.com/), enable OAuth2 for it and add the credentials to your Scrollback server-config.js file. See server-config-template.js or server-config-defaults.js to see how.
