### ISSUE TITLE
RECOMMENDED BY SCROLLBACK

### ISSUE THREAD

**Issue by metao1** [scrollback/scrollback#971]
When the Scrollback decide to recommend : "RECOMMENDED BY SCROLLBACK"
In another word, which condition cause the rooms recommend by Scrollback?

**Comment by aravindet** [comment]
Sorry about the delay. These were demo communities created by people in the Scrollback team. In your self-hosted Scrollback, you can feature rooms using the redis command line (`redis-cli`), switching to the featured module’s database (`select 13` by default) and adding the room id's you want (`sadd featured:room example`).
